### ISSUE TITLE
wrong package description on hex

### ISSUE THREAD

**Issue by petrus-jvrensburg** [elixir-cldr/cldr_units_sql#5]
<img width="837" alt="Screenshot 2023-08-27 at 09 00 46" src="https://github.com/elixir-cldr/cldr_units_sql/assets/3660183/c253d24d-61bf-404e-8b08-8df34ed42369">

**Comment by kipcole9** [comment]
I've fixed the description (thanks for the issue) and pushed a docs release but that doesn't appear to fix the project description. Seems I'll have to push a "null" update to get that changed.

**Comment by kipcole9** [comment]
Published [ex_cldr_units_sql version 1.0.1](https://hex.pm/packages/ex_cldr_units_sql/1.0.1) and the project description is now updated.

**Comment by petrus-jvrensburg** [comment]
Thanks!
